[display]
### Display settings
fullscreen=true
viewport=1920x1200
screen=1
multi-sampling=true
no-vsync=true
frameless=true

[gource]
### Behaviour values
# disable-auto-skip=true
auto-skip-seconds=.5
seconds-per-day=3
max-file-lag=1
file-idle-time=0
elasticity=0.015
max-user-speed=315
user-friction=.5

## Appearance
# title=My Title
# logo=logo.png
font-size=16
background-colour=151515

bloom-intensity=0.5
bloom-multiplier=0.5

hide=progress,mouse

### Highlighting
highlight-colour=FFD700
highlight-users=false
highlight-dirs=false

## Misc
camera-mode=overview
key=true
stop-at-end=true
colour-images=true
user-image-dir=./Dokumentation/Avatars
# default-user-image=./gource/default_avatar.png

### Captions
# caption-file=./gource/captions.txt
caption-size=12px
caption-colour=ffffff
caption-duration=5
caption-offset=-100px